{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Application Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "nodejs_version_info",
     "type": "stat",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nodejs_version_info" }
     ]
    },
    {
     "title": "nodejs_heap_size_used_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "nodejs_heap_space_size_used_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_used_bytes",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "nodejs_heap_size_total_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "nodejs_gc_duration_seconds_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 25 },
     "targets": [
      { "expr": "nodejs_gc_duration_seconds_sum", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "EventLoop Lag p50 seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_p50_seconds{job=\"nestjs-service\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "nodejs_eventloop_lag_p99_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 33 },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_p99_seconds",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "nodejs_eventloop_lag_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
     "targets": [
      { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Active Request Total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 6, "y": 41 },
     "targets": [
      {
       "expr": "nodejs_active_requests_total{job=\"nestjs-service\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "active handles total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 13, "y": 41 },
     "targets": [
      {
       "expr": "nodejs_active_handles_total{job=\"nestjs-service\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
       "legendFormat": "User CPU - {{instance}}"
      },
      {
       "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
       "legendFormat": "Sys CPU - {{instance}}"
      }
     ]
    },
    {
     "title": "Event Loop Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node.js Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(nodejs_version_info{instance=~\"$instance\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Process Restart Times",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Process Memory - {{instance}}"
      },
      {
       "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Total - {{instance}}"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}}"
      },
      {
       "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "External Memory - {{instance}}"
      }
     ]
    },
    {
     "title": "Active Handlers/Requests Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
       "legendFormat": "Active Handler - {{instance}}"
      },
      {
       "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
       "legendFormat": "Active Request - {{instance}}"
      }
     ]
    },
    {
     "title": "Heap Total Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Total - {{instance}} - {{space}}"
      }
     ]
    },
    {
     "title": "Heap Used Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}} - {{space}}"
      }
     ]
    },
    {
     "title": "Heap Available Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}} - {{space}}"
      }
     ]
    }
   ]
  }
 ]
}